//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_17.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklad
    {
        public int id { get; set; }
        public string naimenov { get; set; }
        public int kolichestvo { get; set; }
        public decimal cena { get; set; }
        public int StatuslID { get; set; }
        public int ZakazID { get; set; }
        public int RoleID { get; set; }
        public int SotrudnikiID { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Status Status { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
